package dev.futurepath.views;
import dev.futurepath.controllers.CreateTeamController;
import dev.futurepath.controllers.exceptions.WrongNameException;
import dev.futurepath.model.Player;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Elena Cirstea
 */
public class CreateTeamPanel extends javax.swing.JPanel {
    private CreateTeamController controller;
    /**
     * Creates new form CreateTeamPanel
     */
    public CreateTeamPanel() {
        initComponents();
        controller = new CreateTeamController(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        teamNameTF = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        playersListCB = new javax.swing.JComboBox<>();
        createBT = new javax.swing.JButton();

        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Team's name:");
        add(jLabel1);
        jLabel1.setBounds(20, 40, 90, 17);
        add(teamNameTF);
        teamNameTF.setBounds(120, 40, 180, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Players:");
        add(jLabel2);
        jLabel2.setBounds(20, 100, 100, 20);

        add(playersListCB);
        playersListCB.setBounds(130, 100, 150, 22);

        createBT.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        createBT.setText("Create Team");
        createBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createBTActionPerformed(evt);
            }
        });
        add(createBT);
        createBT.setBounds(200, 190, 120, 25);
    }// </editor-fold>//GEN-END:initComponents

    private void createBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createBTActionPerformed
        String message = "";
        try {
            // botón para crear un equipo
            controller.createTeam();
            message = "Team created.";
        } catch (WrongNameException ex) {
            message = ex.getMessage();
        }finally {
            JOptionPane.showMessageDialog(null, message);
        }
    }//GEN-LAST:event_createBTActionPerformed
      //getters and setters
    public void setTeamNameTF(JTextField teamNameTF) {
        this.teamNameTF = teamNameTF;
    }
  
    public JTextField getTeamNameTF() {
        return teamNameTF;
    }

    public JComboBox<Player> getPlayersListCB() {
        return playersListCB;
    }

    public void setPlayersListCB(JComboBox<Player> playersListCB) {
        this.playersListCB = playersListCB;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createBT;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JComboBox<Player> playersListCB;
    private javax.swing.JTextField teamNameTF;
    // End of variables declaration//GEN-END:variables
}
