package dev.futurepath.views;
import dev.futurepath.controllers.PlayerController;
import dev.futurepath.controllers.exceptions.NoTeamSelectedException;
import dev.futurepath.controllers.exceptions.WrongNameException;
import dev.futurepath.controllers.exceptions.WrongNumberException;
import dev.futurepath.model.Team;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

public class CreatePlayerPanel extends javax.swing.JPanel {
    //atributo
    private PlayerController controller;
   
    //constructor
    public CreatePlayerPanel() {
        initComponents();
        controller = new PlayerController(this);
        //añade un equpo por defecto
        ((DefaultComboBoxModel)cbTeam.getModel()).addElement(new Team(1, "Real Madrid", null));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblId = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        cbTeam = new javax.swing.JComboBox<>();
        btnCreatePlayer = new javax.swing.JButton();
        txtNumber = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setLayout(null);

        lblId.setText("Id");
        add(lblId);
        lblId.setBounds(30, 40, 45, 16);

        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        add(txtName);
        txtName.setBounds(210, 60, 140, 26);

        add(cbTeam);
        cbTeam.setBounds(150, 140, 210, 26);

        btnCreatePlayer.setText("Create user");
        btnCreatePlayer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreatePlayerActionPerformed(evt);
            }
        });
        add(btnCreatePlayer);
        btnCreatePlayer.setBounds(170, 190, 130, 29);
        add(txtNumber);
        txtNumber.setBounds(210, 100, 140, 26);

        jLabel1.setText("Name:");
        jLabel1.setToolTipText("");
        add(jLabel1);
        jLabel1.setBounds(30, 70, 140, 20);

        jLabel2.setText("Number:");
        add(jLabel2);
        jLabel2.setBounds(30, 100, 140, 20);

        jLabel3.setText("Team:");
        add(jLabel3);
        jLabel3.setBounds(30, 140, 46, 20);
    }// </editor-fold>//GEN-END:initComponents
    
    //botón de crear jugador
    private void btnCreatePlayerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreatePlayerActionPerformed
        String message = "";
        try {
            controller.createPlayer();
            message = "Player created.";
        } catch (NoTeamSelectedException | WrongNameException | WrongNumberException ex) {
            message = ex.getMessage();
        } finally {
            JOptionPane.showMessageDialog(null, message);
        }
    }//GEN-LAST:event_btnCreatePlayerActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed
    //getters and setters
    public JLabel getLblId() {
        return lblId;
    }

    public JTextField getTxtName() {
        return txtName;
    }

    public JComboBox<Team> getCbTeam() {
        return cbTeam;
    }

    public JTextField getTxtNumber() {
        return txtNumber;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreatePlayer;
    private javax.swing.JComboBox<Team> cbTeam;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblId;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtNumber;
    // End of variables declaration//GEN-END:variables
}
