package dev.futurepath.views;
import dev.futurepath.controllers.DeletePlayerController;
import dev.futurepath.controllers.PlayerController;
import dev.futurepath.model.Player;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author Elena Cirstea
 */
public class DeletePlayerPanel extends javax.swing.JPanel {
    //atributo
      private DeletePlayerController controller;
    /**
     * Creates new form DeletePlayerPanel
     */
      //constructor
    public DeletePlayerPanel() {
        initComponents();
        controller = new DeletePlayerController(this);
        controller.loadPlayers();
     /*   listPlayers.addItemListener(new ItemListener() {
            @Override
            public void itemStateChanged(ItemEvent e) {
            //listPlayers.getSelectedItem();
                //System.out.println("Vuelve a cargar desde al item listener");
            //controller.loadPlayers();
            Player player;
           // player = controller.getPlayerToDelete();
            
            //controller.setPlayerIntoTheInterface( player);
            
            }
        } );*/
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        listPlayers = new javax.swing.JComboBox<>();
        deleteBTN = new javax.swing.JToggleButton();

        setLayout(null);

        jLabel1.setText("Player:");
        add(jLabel1);
        jLabel1.setBounds(20, 30, 100, 20);

        add(listPlayers);
        listPlayers.setBounds(120, 30, 210, 26);

        deleteBTN.setText("Delete");
        deleteBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBTNActionPerformed(evt);
            }
        });
        add(deleteBTN);
        deleteBTN.setBounds(140, 140, 77, 29);
    }// </editor-fold>//GEN-END:initComponents

    private void deleteBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBTNActionPerformed
        // TODO add your handling code here:
       
     System.out.println("Entra en el boton de borrar");
     controller.deletePlayer();
     String message = "Player deleted.";
     JOptionPane.showMessageDialog(null, message);
  
        
    }//GEN-LAST:event_deleteBTNActionPerformed

    public JComboBox<Player> getListPlayers() {
        return listPlayers;
    }

    public void setListPlayers(JComboBox<Player> listPlayers) {
        this.listPlayers = listPlayers;
    }
    
            

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton deleteBTN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JComboBox<Player> listPlayers;
    // End of variables declaration//GEN-END:variables
}
