/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dev.futurepath.views;

import dev.futurepath.controllers.ListPlayerController;
import dev.futurepath.model.Player;
import javax.swing.DefaultListModel;
import javax.swing.JComboBox;
import javax.swing.JList;

/**
 *
 * @author Elena Cirstea
 */
public class ListPlayersPanel extends javax.swing.JPanel {

    /**
     * Creates new form ListPlayersPanel
     */
    //atributo controller
    private ListPlayerController controller;
    
    public ListPlayersPanel() {
        initComponents();
        controller = new ListPlayerController(this);
        System.out.println("antes del null pointer");
        controller.loadPlayers();
        
    }

    public void setCBplayers(JComboBox<Player> CBplayers) {
        this.CBplayers = CBplayers;
    }

    public JComboBox<Player> getCBplayers() {
        return CBplayers;
    }
    
  
          
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CBplayers = new javax.swing.JComboBox<>();

        setLayout(new java.awt.BorderLayout());

        add(CBplayers, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<Player> CBplayers;
    // End of variables declaration//GEN-END:variables

   
}
