/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dev.futurepath.views;

import dev.futurepath.controllers.ListPlayerController;
import dev.futurepath.model.Player;
import javax.swing.JList;

/**
 *
 * @author Elena Cirstea
 */
public class ListPlayers2Panel extends javax.swing.JPanel {

    /**
     * Creates new form ListPlayers2Panel
     */
    private ListPlayerController controller;
    
    public ListPlayers2Panel() {
        initComponents();
        controller = new ListPlayerController(this);
        System.out.println("antes del null pointer");
        controller.populateAll();
    }
     
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        listPlayers = new javax.swing.JList<>();

        setLayout(new java.awt.BorderLayout());

        jScrollPane1.setViewportView(listPlayers);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    public JList<Player> getListPlayers() {
        return listPlayers;
    }

    public void setListPlayers(JList<Player> listPlayers) {
        this.listPlayers = listPlayers;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<Player> listPlayers;
    // End of variables declaration//GEN-END:variables
}
