/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dev.futurepath.views;

import dev.futurepath.model.Team;
import javax.swing.JList;

/**
 *
 * @author Ele
 */
public class ListTeamPanel extends javax.swing.JPanel {
    //atributte
    
    //constructor
    public ListTeamPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        listTeams = new javax.swing.JList<>();

        setLayout(new java.awt.BorderLayout());

        jScrollPane1.setViewportView(listTeams);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    
    //getters and setters for the list
    public JList<Team> getListTeams() {
        return listTeams;
    }

    public void setListTeams(JList<Team> listTeams) {
        this.listTeams = listTeams;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<Team> listTeams;
    // End of variables declaration//GEN-END:variables
}
