package dev.futurepath.views;
import dev.futurepath.controllers.UpdatePlayerController;
import dev.futurepath.controllers.exceptions.NoTeamSelectedException;
import dev.futurepath.controllers.exceptions.WrongNameException;
import dev.futurepath.controllers.exceptions.WrongNumberException;
import dev.futurepath.model.Player;
import java.awt.event.ItemEvent;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Elena Cirstea
 */
public class UpdatePlayersPanel extends javax.swing.JPanel {

    //atributo controller
    private UpdatePlayerController controller;
    
    //constructor
    public UpdatePlayersPanel() {
        initComponents();
        controller = new UpdatePlayerController(this);
        controller.loadPlayers();
        CBplayers.addItemListener((ItemEvent e) -> {
            Player player1 = (Player) CBplayers.getSelectedItem();
            nameTF.setText(player1.getName());
            numberTF.setText("" + player1.getNumber());
        });
    }   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CBplayers = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        nameTF = new javax.swing.JTextField();
        numberTF = new javax.swing.JTextField();
        teamCB = new javax.swing.JComboBox<>();
        updateBT = new javax.swing.JToggleButton();

        setLayout(null);

        add(CBplayers);
        CBplayers.setBounds(200, 30, 160, 26);

        jLabel1.setText("Name:");
        add(jLabel1);
        jLabel1.setBounds(20, 80, 47, 20);

        jLabel2.setText("Number:");
        add(jLabel2);
        jLabel2.setBounds(20, 120, 60, 20);

        jLabel3.setText("Team:");
        add(jLabel3);
        jLabel3.setBounds(20, 160, 50, 20);

        jLabel4.setText("Choose Player:");
        add(jLabel4);
        jLabel4.setBounds(20, 30, 120, 20);
        add(nameTF);
        nameTF.setBounds(210, 90, 150, 26);

        numberTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberTFActionPerformed(evt);
            }
        });
        add(numberTF);
        numberTF.setBounds(210, 120, 150, 26);

        add(teamCB);
        teamCB.setBounds(200, 160, 170, 26);

        updateBT.setText("Update Player");
        updateBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBTActionPerformed(evt);
            }
        });
        add(updateBT);
        updateBT.setBounds(230, 230, 131, 29);
    }// </editor-fold>//GEN-END:initComponents

    private void numberTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numberTFActionPerformed

    private void updateBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBTActionPerformed
        // llamar al controller para actualizar
         String message = "";
      
        try {
               controller.updatePlayer();
        message = "Player updated.";
        } catch (NoTeamSelectedException | WrongNameException | WrongNumberException ex) {
            message = ex.getMessage();
        } finally {
            JOptionPane.showMessageDialog(null, message);
        }
    }//GEN-LAST:event_updateBTActionPerformed
   
    //getters y setters
    public JTextField getNameTF() {
        return nameTF;
    }

    public void setNameTF(JTextField nameTF) {
        this.nameTF = nameTF;
    }

    public JTextField getNumberTF() {
        return numberTF;
    }
    
    public void setNumberTF(JTextField numberTF) {
        this.numberTF = numberTF;
    }

    public void setTeamCB(JComboBox<String> teamCB) {
        this.teamCB = teamCB;
    }

    public JComboBox<String> getTeamCB() {
        return teamCB;
    }

    public JComboBox<Player> getCBplayers() {
        return CBplayers;
    }

    public void setCBplayers(JComboBox<Player> CBplayers) {
        this.CBplayers = CBplayers;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<Player> CBplayers;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField nameTF;
    private javax.swing.JTextField numberTF;
    private javax.swing.JComboBox<String> teamCB;
    private javax.swing.JToggleButton updateBT;
    // End of variables declaration//GEN-END:variables

  
}
